config/routes.rb
ProudErrorRails::Application.routes.draw do
  match "/cause.js", :to => "partners#cause_js", :as => "cause_js_partners", :via => :get
  root :to => 'welcome#index'

  resources :contacts, :only => [:create]
  get "/partners", :to => "partners#new", :as => "index_partner"
  resources :partners do
    member do
      get 'cause'
    end

    collection do
      get 'list'
    end
  end

  # named routes for cause listing, individual cause etc
  match "/causes", :to => "causes#index", :as => "causes"
  match "/causes/:theme", :to => "causes#list_theme", :as => "list_theme_causes"
  match "/causes/:theme/show/:title/:project_identifier", :to => "causes#show", :as => "cause"

  #named routes for displaying full or partial causes
  match "/causes/:uuid/display/full", :to => "causes#display_full", :as => "display_full_cause"
  match "/causes/:uuid/display/section", :to => "causes#display_section", :as => "display_section_cause"
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :url, :code, :theme

  VALID_URL_REGEX_SET = /^(https?:\/\/(w{3}\.)?)|(w{3}\.)|[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix
  validates :url, :uniqueness => true, :format => { :with => VALID_URL_REGEX_SET }
  validates :code, :presence => true, :uniqueness => true

  scope :order_descended_creation, order("partners.created_at DESC")

  scope :active, where(:active => true)

  before_validation :sanitize_url, :assign_code

  class << self
    def ordered_active
      active.order_descended_creation
    end
    
    def set_url(url)
      url.gsub(/^(https?:\/\/(w{3}\.)?)| w{3}\./ix,"")
    end
  end #end of the self block

  def set_theme(theme_name)
    if theme_name.present? && Cause::ALL_THEMES.downcase != theme_name.to_s.strip.downcase
      self.theme = theme_name
      self.save
    end
  end

  def has_theme?
    self.theme.present?
  end

  private
  def sanitize_url
    self.url = self.url.to_s.gsub(/^(https?:\/\/(w{3}\.)?)| w{3}\./ix, "")
  end
  
  def assign_code
    self.code = UUIDTools::UUID.random_create.to_s.gsub(/[-]/, "")
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  include Rails.application.routes.url_helpers # brings ActionDispatch::Routing::UrlFor
  include ActionView::Helpers::TagHelper
  
  before_filter :fetch_partner, :check_partner_exists,:only => [:create]

  def list
    @partners = Partner.ordered_active
  end

  def new
    @partner = Partner.new
	end

	def create
    @partner = Partner.new(params[:partner])
    respond_to do |format|
      if @partner.save
        format.html {render :text => cause_full_path}
          format.json {render :json => {:src => cause_full_path, :code => @partner.code}.to_json}
      else
        status = :unprocessable_entity
        format.html {render :text => @partner.errors.full_messages, :status => status}
        format.json {render :json => {:url => @partner.errors.full_messages.first.gsub(/Url/, "URL")}.to_json, :status => status}
      end
    end
	end

  def cause_js
    code = params[:code]
    @partner = Partner.find_by_code(code)
    respond_to do |format|
      format.html {response.headers['Content-Type'] = "application/javascript";render :partial => "partners/cause.js"}
      format.js {response.headers['Content-Type'] = "application/javascript";render :partial => "partners/cause.js"}
    end
  end

  private
  def check_partner_exists
    if fetch_partner.present?
      set_theme
      respond_to do |format|
        format.html {render :text => cause_full_path}
        format.json {render :json => {:src => cause_full_path, :code => @partner.code}.to_json}
      end
      false
    end
  end

  def set_theme
    fetch_partner.set_theme(params[:partner][:theme])
  end
  
  def fetch_partner
    @partner ||= Partner.find_by_url(Partner.set_url(params[:partner][:url]))
  end

  def cause_full_path
    "http://#{SiteConfig.app_base_url}#{cause_partner_path(@partner.code)}"
  end
  
  def fetch_template_code
    template = Template.new(Rails.root.join('app', 'views'))
    template.assign(:partner =>  @partner, :cause => @cause)
    template.render(:template => 'partners/cause.html.erb')
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
  def tableize_partners(partners)
    partners_table = []
    unless partners.blank?
      add_blank_partners(partners)

      partners.each_slice(3) do |partners_slice|
        partners_table << partners_slice
      end

      list1 = []; list2 = []; list3 = []

      partners_table.each do |partners_row|
        list1 << partners_row[0]
        list2 << partners_row[1]
        list3 << partners_row[2]
      end

      [list1, list2, list3]
    end
  end

  def add_blank_partners(partners)
    while 0 != (partners.length % 3)
      partners << Partner.new()
    end
  end
end

app/views/partners/_cause.js.erb
<% unless "partial" == params[:section] %>
  <%= complete_page_replacement_script %>
<% else %>
  <%= partial_page_replacement_script %>
<% end %>

app/views/partners/_items.html.erb
<% items.each do |partner_item| %>
  <li>
    <% unless partner_item.new_record? %>
      <% link = "http://#{partner_item.url}" %>
      <%= link_to(link, link, :target => "_blank") %>
    <% else %>
      &nbsp;
    <% end %>
  </li>
<% end %>

app/views/partners/list.html.erb
<% list1, list2, list3 = tableize_partners(@partners) %>
<div class="container">
  <div class="participatingweb">
    <h2>
      <%= image_tag("participants.png", :alt => "Participating Websites") %>
    </h2>
    <div class="col pull-left">
      <ul class="listing1">
        <%= render(:partial => "partners/items", :locals => {:items => list1}) %>
      </ul>
    </div>
    <div class="col pull-left">
      <ul class="listing1">
        <%= render(:partial => "partners/items", :locals => {:items => list2}) %>
      </ul>
    </div>
    <div class="col pull-left last">
      <ul class="listing1">
        <%= render(:partial => "partners/items", :locals => {:items => list3}) %>
      </ul>
    </div>
  </div>
</div>

app/views/partners/new.html.erb
<div class="container" id="partner_form_container">
  <div class="pull-left illustimage">
    <%= image_tag("patched_parachute.png", :alt => "parachute") %>
  </div>
  <div class="pull-right registerform res_width_auto">
    <h2>
      <%= image_tag("registration_title.png", :alt => "Register your website") %>
    </h2>
    <%= simple_form_for(:partner, :url => partners_path(:format => :json),
      :html => {:class => 'horizontal-form', :id => "partner_form"},
      :remote => true) do |f| %>

      <%= f.input :theme, :collection => @theme_names,
        :label => "Choose Cause Category:",
        :label_html => {:class => ""},
        :required => false,
        :prompt => "Any Category",
        :input_html => {:class => ''} %>

      <%= f.input :url,
        :input_html => {:class => 'input', :maxlength => 50},
        :label => "Your Website URL:",
        :label_html => {:class => ""},
        :required => false,
        :placeholder => 'www.example.com' %>

      <%= submit_tag("Next", :class => "nextbutton") %>
      <span class="loading">Please Wait...</span>
    <% end %>

  </div>
</div>

<div class="embedcode">
  <h2>
    <%= image_tag("embedcode.png", :alt => "Embed Code Title") %>
  </h2>
  <div class="middlecont">
    <div class="fullpage pull-left embedcodeContainer">
      <h3>
        <%= image_tag("full_page_title.png", :alt => "Full page") %>
      </h3>
      <div class="outerbox">
        <div class="iframeCode" id="partner_page_uuid"></div>
        <div class="actions">
          <%= link_to("", "javascript:void(0)", :class => "scrollToHow", :title => "How it works?") %>
          <%= link_to("", "javascript:void(0)", :class => "copyToClipboard", :title => "Copy") %>
        </div>
      </div>
    </div>
    <div class="orbox">
      <span class="helper"></span>
      <%= image_tag("orbg.png", :alt => "OR") %>
    </div>
    <div class="fullpage pull-right embedcodeContainer">
      <h3>
        <%= image_tag("section_page_title.png", :alt => "Section of a Page") %>
      </h3>
      <div class="outerbox">
        <div class="iframeCode" id="partner_section_uuid"></div>
        <div class="actions">
          <%= link_to("", "javascript:void(0)", :class => "scrollToHow", :title => "How it works?") %>
          <%= link_to("", "javascript:void(0)", :class => "copyToClipboard", :title => "Copy") %>
        </div>
      </div>
    </div>
  </div>
  <h3 class="meassage">
    Thank you for supporting prouderros.org. Spread the word.
  </h3>
  <div class="socialIcons">
    <%= link_to('<span class="fb">facebook</span>'.html_safe,"#",:onclick => "postToFeed(); return false;", :class => "pull-left SocialLink") %>
    <%= link_to('<span class="twit">twitter</span>'.html_safe, "http://twitter.com/share?url=http%3A%2F%2Fprouderrors.org%2F&text=Give meaning to your 404 ERROR pages! via Proud error", :class => "pull-right SocialLink", :target => "_blank") %>
  </div>
</div>
<%= hidden_field_tag :app_base_url, SiteConfig.app_base_url %>

<div id='fb-root'></div>
<script src='http://connect.facebook.net/en_US/all.js'></script>
<script type="text/javascript">
  FB.init({appId: "<%= FACEBOOK_CONFIG[:app_id] %>", status: true, cookie: true});

  function postToFeed() {

    // calling the API ...
    var obj = {
      method: 'feed',
      link: 'http://www.prouderrors.org/',
      picture: 'http://www.prouderrors.org/assets/cause.png',
      name: 'Proud Errors',
      caption: '404s for a cause.',
      description: 'MAKE BETTER USE OF YOUR ERROR PAGES. Rather than being ashamed of your website errors, be proud of them.Install our application and we\'ll publish a beautiful error page with a global cause, every time a page is not found or an error occurs on your website.Together we can make a difference.'
    };

    function callback(response) {
      document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
    }

    FB.ui(obj, callback);
    return false;
  }
</script>