config/routes.rb
ProudErrorRails::Application.routes.draw do
  match "/cause.js", :to => "partners#cause_js", :as => "cause_js_partners", :via => :get
  root :to => 'welcome#index'

  resources :contacts, :only => [:create]
  get "/partners", :to => "partners#new", :as => "index_partner"
  resources :partners do
    member do
      get 'cause'
    end

    collection do
      get 'list'
    end
  end

  # named routes for cause listing, individual cause etc
  match "/causes", :to => "causes#index", :as => "causes"
  match "/causes/:theme", :to => "causes#list_theme", :as => "list_theme_causes"
  match "/causes/:theme/show/:title/:project_identifier", :to => "causes#show", :as => "cause"

  #named routes for displaying full or partial causes
  match "/causes/:uuid/display/full", :to => "causes#display_full", :as => "display_full_cause"
  match "/causes/:uuid/display/section", :to => "causes#display_section", :as => "display_section_cause"
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  before_filter :themes_hash
  before_filter :populate_display_vars, :only => [:display_full, :display_section]

  def index
    redirect_to list_theme_causes_path(@themes.first['theme'].parameterize)
  end

  def list_theme
    @causes = Cause.for_a_theme(params[:theme])
    @title = "#{params[:theme].titleize} - Proud Errors"
  end

  def show
    @cause = Cause.find_by_project_identifier(params[:project_identifier])
    @title = "#{@cause.title}"
  end

  def display_full
    
    respond_to do |format|
      format.html {render :layout => "proud_error"}

      #code to fetch the action view html
      av = action_view
      av.assign({:partner => @partner, :cause => @cause})
      format.json {render :text => "jQuery('body').html('#{av.render(:file => "causes/display_full.html.erb", :layout => "layouts/proud_error.html.erb", :handlers => [:erb]).gsub(/\n/, "")}')"}
    end
  end

  def display_section
    respond_to do |format|
      format.html {render :layout => "proud_error"}

      #code to fetch the action view html
      av = action_view
      av.assign({:partner => @partner, :cause => @cause})
      format.json {render :text => "jQuery('#proudErrorContainer').html('#{av.render(:file => "causes/display_section.html.erb", :layout => "layouts/blank.html.erb", :handlers => [:erb]).gsub(/\n/, "")}')"}
    end
  end

  private
  def populate_display_vars
    @partner = Partner.find_by_code(params[:uuid])
    @partner.update_attribute(:active, true)
    @cause = Cause.fetch(@partner)
  end

  def themes_hash
    @themes = Cause.cached_themes
  end

  def action_view
    controller = ActionController::Base.new
    controller.request = ActionDispatch::TestRequest.new
    TaskActionView.new(Rails.root.join('app', 'views'), {}, controller)
  end

  class TaskActionView < ActionView::Base
    include Rails.application.routes.url_helpers
    include ApplicationHelper

    def default_url_options
      {:host =>  SiteConfig.app_base_url}
    end

    def protect_against_forgery?
      false
    end
  end
end

app/helpers/causes_helper.rb
module CausesHelper
  def active_class(theme_hash)
    params['theme'] == theme_hash['theme'].parameterize ? "active" : ""
  end
end

app/views/causes/_themes.html.erb
<ul class="listing2">
  <% themes.each do |theme|  %>
    <li class="<%= active_class(theme) %>">
      <%= link_to("#{theme['theme']}".html_safe, list_theme_causes_path(theme['theme'].parameterize)) %>
    </li>
  <% end %>
</ul>

app/views/causes/display_full.html.erb
<link type="text/css" rel="stylesheet" media="all" href="http://<%= SiteConfig.app_base_url %>/cause_assets/proud_error.css" />
<script type="text/javascript" src="//use.typekit.net/ohv6wko.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
<div class="header">
  <img src="<%= "http://#{SiteConfig.app_base_url}/assets/pe_bird.png" %>" alt="bird"  class="bird" />
  <img src="<%= "http://#{SiteConfig.app_base_url}/assets/pe_sun.png" %>" alt="sun"  class="sun" />

  <div class="container">
    <div class="logo"><a href="http://<%= SiteConfig.app_base_url %>" target="_blank"> <img src="http://<%= SiteConfig.app_base_url %>/assets/img.png" alt="errorImg"/></a></div>
    <div class="title">
      <h1><img src="http://<%= SiteConfig.app_base_url %>/assets/pe_oops_message.gif" alt="errorImg" /></h1>
      <h2>We are proud of it though, as it now provides an opportunity for us to do some social good.</h2>
    </div>
  </div>
</div>

<div class="causeContainer">
  <div class="causeHeader"></div>

  <div class="causeInformation">
    <table width="80%" cellpadding="5" cellspacing="0" border="0">
      <tr>
        <td class="image"><%= image_tag(@cause.medium_image_url) %></td>
        <td class="description">
          <h2> <%= @cause.title %></h2>
          <div class="summary"><%= @cause.summary %></div>
          <div class="navigation">
            <%= link_to("", @cause.project_url, :title => "Yes I want to help", :class => "causeLink", :target => "_blank") %>
            <%= link_to("Back to the homepage", "http://www.#{@partner.url}", :class => "backToHome") %>
          </div>
        </td>
      </tr>
    </table>
  </div>

  <div class="causeFooter"></div>
</div>

<div class="footer">
  <div class="poweredBy">
    A conscious initiative by
    <%= link_to "Ruby on Rails Development Team", "http://www.idyllic-software.com", :target => "_blank" %> @ <%= link_to("Idyllic Software", "http://www.idyllic-software.com", :target => "_blank") %>
  </div>
</div>

app/views/causes/display_section.html.erb
<div class="causeInformation">
  <table width="100%" cellpadding="5" cellspacing="0" border="0">
    <tr>
      <td class="image">
        <%= image_tag(@cause.medium_image_url) %>
        <br />
        <span class="prouderrorLink">
          <%= link_to("Powered by Proud Errors", "http://www.prouderrors.org") %>
        </span>
      </td>
      <td class="description">
        <h2 class="title"> <%= @cause.title %></h2>
        <div class="summary"><%= @cause.summary %></div>
        <div class="navigation">
          <%= link_to("Yes, I want to help", @cause.project_url, :title => "Yes I want to help", :class => "causeLink", :target => "_blank") %>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/causes/list_theme.html.erb
<div class="container">
  <div class="allcauses">
    <h2>
      <%=  image_tag("all_causes.png", :alt => "causes") %>
    </h2>

    <div class="breadcrumb clearfix">
      <ul class="pull-left">
        <li>
          <%= link_to "Causes", causes_path %>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <%= params[:theme].titleize %>
        </li>
      </ul>
    </div>

    <div class="verticalnav pull-left">
      <%= render(:partial => "causes/themes", :locals => {:themes => @themes}) %>
    </div>
    <div class="linksbox pull-left">
      <ul class="listing1">
        <% if @causes.present? %>
          <% @causes.each do |cause| %>
            <li>
              <%= link_to cause.title, cause_path(cause.theme.parameterize, cause.title.parameterize, cause.project_identifier) %>
            </li>
          <% end %>
        <% else %>
          <li>
            No Active initiatives for this category.
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/causes/show.html.erb
<div class="container" id="wrapper">
  <div class="allcauses">
    <h2>
      <%=  image_tag("the_cause.png", :alt => "causes") %>
    </h2>

    <div class="breadcrumb clearfix">
      <ul class="pull-left">
        <li>
          <%= link_to "Causes", causes_path %>
          <span class="divider">/</span>
        </li>
        <li>
          <%= link_to @cause.theme, list_theme_causes_path(@cause.theme.parameterize) %>
          <span class="divider">/</span>
        </li>
        <li class="active">
          <%= @cause.title %>
        </li>
      </ul>
    </div>

    <div class="causeContainer">
      <div class="causeInformation">
        <table width="100%" cellpadding="5" cellspacing="0" border="0">
          <tr>
            <td class="image"><%= image_tag(@cause.medium_image_url) %>
            </td>
            <td class="description">
              <h2 class="causeTitle"> <%= @cause.title %></h2>
              <div class="summary"><%= @cause.summary %></div>
              <div class="navigation">
                <%= link_to("", @cause.project_url, :title => "Yes I want to help", :class => "causeLink", :target => "_blank") %>
              </div>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

<% content_for :meta_description do %>
  <meta name="Description" content="<%= @cause.summary %>" />
<% end %>