config/routes.rb
ProudErrorRails::Application.routes.draw do
  match "/cause.js", :to => "partners#cause_js", :as => "cause_js_partners", :via => :get
  root :to => 'welcome#index'

  resources :contacts, :only => [:create]
  get "/partners", :to => "partners#new", :as => "index_partner"
  resources :partners do
    member do
      get 'cause'
    end

    collection do
      get 'list'
    end
  end

  # named routes for cause listing, individual cause etc
  match "/causes", :to => "causes#index", :as => "causes"
  match "/causes/:theme", :to => "causes#list_theme", :as => "list_theme_causes"
  match "/causes/:theme/show/:title/:project_identifier", :to => "causes#show", :as => "cause"

  #named routes for displaying full or partial causes
  match "/causes/:uuid/display/full", :to => "causes#display_full", :as => "display_full_cause"
  match "/causes/:uuid/display/section", :to => "causes#display_section", :as => "display_section_cause"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :set_title

  def index
#    @participating_count = Partner.active.count
    @theme_names = get_theme_names
  end

  private
  def get_theme_names
    cached_themes = Cause.cached_theme_names
  end

  def set_title
    @title = "Recycle 404 Error Pages"
  end
end

app/views/welcome/_fblike.html.erb
<!-- Facebook Like -->
    <div id="fb-root"></div>
      <script>
        (function(d, s, id) 
          {var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
              fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));
      </script>

    <div class="fb-like" data-href="http://prouderrors.org" data-send="false" data-width="450" data-show-faces="false"></div>

app/views/welcome/index.html.erb
<div id="illustration">
  <div class="container">
    <div id="introduction_container">
    <div class="pull-left illustimage">
      <%= image_tag("pic_man.png") %>
    </div>
    <div class="pull-right res_width_auto websiteerrors">
      <h2>
        <%= image_tag("website_error.png", :alt => "Registration Title") %>
      </h2>
      <h3>Recycle your 404 error pages</h3>
      <p>Donate your website 404 page to a cause and be proud of it.</p>
      <p>Install our application and we'll publish a beautiful error page with a global cause, every time a page is not found or an error occurs on your website.</p>
      <p>Together we can make a difference.</p>
      <p class="lookwho">
        <%= link_to("Look who is helping", list_partners_path) %>
      </p>
      <%= link_to("<span class='socialgood'>I am in.  Get me started!</span>".html_safe, "javascript:void(0)", :class => "startbutton getStartedLink") %>
    </div>
    </div>

    <%= render :file => "partners/new" %>

  </div>
</div>

<div id="howitworks">
  <div class="container">
    <div class="column1 pull-left res_width_auto">
      <%= image_tag("404causes.png", :alt => "404 Cause Image") %>
    </div>
    <div class="column2 pull-right res_width_auto">
      <h2>&nbsp;</h2>
      <p class="subtitle">Beautiful and meaningful error pages in minutes!</p>
      <div class="pagedemo clearfix">
        <div class="pull-left">
          <%= image_tag("complete_page.png", :alt => "Complete Page") %>
          <p>Complete Page</p>
        </div>
        <div class="orbox">
          <span class="helper"></span>
          <%= image_tag("orbg.png", :alt => "OR") %>
        </div>
        <div class="pull-right">
          <%= image_tag("page_section.png", :alt => "Complete Page") %>
          <p>Section of Page</p>
        </div>
      </div>
      <div class="prouderrors_pointer"> 
        <%= image_tag("proud_errors.png", :alt => "Proud Errors") %>
      </div>
    </div>
  </div>
</div>

<% content_for :meta_description do %>
  <meta name="Description" content="HTTP 404 stands for Page not found. When a page is not found, this page is generated. ProudErrors enables you to recycle the web waste by displaying a global cause on those pages." />
<% end %>