config/routes.rb
ProudErrorRails::Application.routes.draw do
  match "/cause.js", :to => "partners#cause_js", :as => "cause_js_partners", :via => :get
  root :to => 'welcome#index'

  resources :contacts, :only => [:create]
  get "/partners", :to => "partners#new", :as => "index_partner"
  resources :partners do
    member do
      get 'cause'
    end

    collection do
      get 'list'
    end
  end

  # named routes for cause listing, individual cause etc
  match "/causes", :to => "causes#index", :as => "causes"
  match "/causes/:theme", :to => "causes#list_theme", :as => "list_theme_causes"
  match "/causes/:theme/show/:title/:project_identifier", :to => "causes#show", :as => "cause"

  #named routes for displaying full or partial causes
  match "/causes/:uuid/display/full", :to => "causes#display_full", :as => "display_full_cause"
  match "/causes/:uuid/display/section", :to => "causes#display_section", :as => "display_section_cause"
end

app/views/layouts/_contactable.html.erb
<div id="contactable">
  <!-- contactable html placeholder -->
</div>
<%= hidden_field_tag :contact_form_url, contacts_path %>

app/views/layouts/_footer.html.erb
<footer id="footer">
  <p>A conscious initiative
    by <a href="http://www.idyllic-software.com" target="_blank">Ruby on Rails Development</a> team @
    <a href="http://www.idyllic-software.com" target="_blank">Idyllic Software</a> | Causes courtesy: <a href="http://www.globalgiving.org/" target="_blank">globalgiving</a>
  </p>
  <p>&copy; 2012 Idyllic Software. All Rights Reserved</p>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
  <div class="container">
    <h1 class="pull-left" id="logo">
      <%= link_to("&nbsp;".html_safe, root_path) %>
    </h1>
    <div id="homeright" class="pull-right">
      <%= render(:partial => "layouts/social") %>
    </div>
  </div>
</header>

app/views/layouts/_social.html.erb
<ul class="nav">
<li><%= link_to("View all causes", causes_path()) %></li>
<%# Link to the Facebook page %>
<li class="margin_right"><%= link_to(image_tag('facebook.png'), "http://www.facebook.com/ProudErrors", :target => "_blank") %></li>

<%# Link to the Prouderror Twitter  page %>
<li class="margin_right_none"><%= link_to(image_tag('twiter.png'), "https://twitter.com/prouderrors", :target => "_blank") %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= title_content %>
      <%= yield :title %>
    </title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="//use.typekit.net/ohv6wko.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:title" content="Proud Error"/>
    <meta property="og:site_name" content="Proud Error"/>
    <meta property="og:url" content="http://prouderrors.org"/>
    <meta property="og:image" content="http://www.prouderrors.org/assets/logo.png"/>
    <meta property="og:description" content="Give meaning to your 404 and 500 errors pages with ProudErrors!"/>
    <meta property="http://opengraph.org/schema/title" content="Proud Error"/>
    <meta property="http://opengraph.org/schema/url" content="http://www.prouderrors.org"/>
    <meta property="http://opengraph.org/schema/description" content="Donate your website error page to a cause and be proud of it."/>
    <%= yield :meta_description %>
  </head>
  <body>
    <%= render :partial => "layouts/contactable" %>

    <%= render :partial => "layouts/header" %>

    <%= yield %>
    
    <%= render 'layouts/footer' %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-26787585-5']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </body>
</html>

app/views/layouts/blank.html.erb
<%= yield %>

app/views/layouts/proud_error.html.erb
<%= yield %>